#refreshed !

# Configuration for ALL environments is contained
# within this file.
# To specify an environment at runtime use the
# command line arg --spring.profiles.active=xxx (local, dev, qaA, qaB, prodA, etc.)
#

# Property declarations common to all environments
spring:
  main:
    api-version: 1.0

  data:
    mongodb:
      host: 192.168.99.100
      port: 27017
      database: risk

  profiles:
    active: local

## modifications still needed here; I do consider we should have  default port in our constellation
##  -- which one is that to be discussed
server:
  port: 30002

management:
  context-path: /rmm-metrics/
  port: 30802
endpoints:
  health:
    mapping:
      DOWN: INTERNAL_SERVER_ERROR

#Kafka host should be the one from metabase which is used by their entity-audit component
kafka:
  clientId:             risk-service-${spring.profiles.active}
  kafka-hosts:          kafka-dev-use1-001.moreover.local:9092
  topic:                entity-audit-change
  retries:              5
  acks:                 1

# Property overrides specific to an environment

spring:
  profiles: prod
  data:
    mongodb:
      host:             mongos-prod-use1-001-rmmprod1.moreover.local
      port:             27017

server:
  port: 8080

kafka:
  kafka-hosts:          kafka-prod-use1-001-rmmprod1.moreover.local:9092
  topic:                entity-audit-change
  retries:              5
  acks:                 1


spring:
  profiles: cert
  data:
    mongodb:
      host:             rmmmongodb-cert-use1-001.moreover.local
      port:             27017

server:
  port: 8080

kafka:
  kafka-hosts:          kafka-cert-use1-001.moreover.local:9092
  topic:                entity-audit-change
  retries:              5
  acks:                 1


spring:
  profiles: qa
  data:
    mongodb:
      host:             rmmmongodb-qa-use1-001.moreover.local
      port:             27017

server:
  port: 8080

kafka:
  kafka-hosts:          kafka-qa-use1-001.moreover.local:9092
  topic:                entity-audit-change
  retries:              5
  acks:                 1


spring:
  profiles: dev
  data:
    mongodb:
      host:             rmmmongodb-dev-use1-001.moreover.local
      port:             27017

server:
  port: 8080

kafka:
  kafka-hosts:          kafka-dev-use1-001.moreover.local:9092
  topic:                entity-audit-change
  retries:              5
  acks:                 1


spring:
  profiles: local
  data:
    mongodb:
      host:             192.168.99.100

server:
  port: 30002

kafka:
  kafka-hosts:          192.168.99.100:9092
  topic:                entity-audit-change
  retries:              5
  acks:                 1


spring:
  profiles:             integration-test
  data:
    mongodb:
      host:             192.168.99.100

server:
  port: 30002

kafka:
  kafka-hosts:          192.168.99.100:9092
  topic:                entity-audit-change
  retries:              5
  acks:                 1
