# Configuration for ALL environments is contained
# within this file.
# To specify an environment at runtime use the
# command line arg --spring.profiles.active=xxx (local, dev, qaA, qaB, prodA, etc.)
#

# Property declarations common to all environments
spring:
#  main:
#    web-environment: true

management:
  context-path: /rmm-metrics/
  port: 8888
  health:
    solr:
      enabled: false
  security:
    enabled: false
endpoints:
  health:
    mapping:
      DOWN: INTERNAL_SERVER_ERROR

security:
  basic:
    enabled: false

server:
    port: 8080

# Take into consideration the time an article needs to travel from CREM to Aggregator
appConfig:
  aggregatorArticleEpsilonMinutes: 3

services:
    aggregator:
      endpoints:
        highestRiskEntities: /api/v1/aggregator/highestRiskEntities/
        oldestRiskEntity: /api/v1/aggregator/oldestRiskEntity/
        detailHighRiskEntity: /api/v1/aggregator/detailHighRiskEntity/
        oldestPguid: /api/v1/aggregator/oldestPguid/
        highestIndexTerms: /api/v1/aggregator/highestIndexTerms/
        pestleCounts: /api/v1/aggregator/pestleCounts/
        oldestPestle: /api/v1/aggregator/oldestPestle/

    aggregatorArticleViewer:
      endpoints:
        byRiskEntityId: /api/v1/aggregator-articles/riskEntity/
        byIndexTermPGUID: /api/v1/aggregator-articles/indexTerm/
        byPestle: /api/v1/aggregator-articles/pestle/

    scoringService:
      endpoints:
        articleScores: /api/v1/scoring/articleScores/byIds
        matchedArticles: /api/v1/scoring/matchedArticles/

    riskService:
      endpoints:
        category: /api/v1/risk/category/customer/
        company : /api/v1/risk/companies/
        spreadsheet: /api/v1/risk/spreadsheet/
        tempCompany: /api/v1/risk/templateTempCompanies/
        tempError: /api/v1/risk/templateTempErrors/

    previewService:
      endpoints:
        preview: /api/v1/preview/articles/

    feedApiInterfaceService:
      endpoints:
        feed: /feed/api/v1/

    feedManager:
      endpoints:
        feed:  /api/v1/feedmanager/feed/
        feeds: /api/v1/feedmanager/feeds/
        feedsCount: /api/v1/feedmanager/feeds/count/

    feedContent:
      endpoints:
        feedContentByFeed:  /api/v1/feedcontent/

    customerService:
      endpoints:
        customer: /api/v1/customer/
        loggedInUser: /api/v1/customer/loggedInUser/
        user: /api/v1/customer/user/

    universalUser:
      endpoints:
        profile: /universaluser/api/v1/
        loginToken: /universaluser/api/v1/token
        passwordRequest: /universaluser/api/v1/password/request
        passwordReset: /universaluser/api/v1/password/reset
      contentPermissions:
        toInclude: 335
        toExclude:

    solr:
      endpoints:
        umbra: /umbra/api/search


feed-server:
  host:                     192.168.99.100
  port:                     30006
  endpoint:                 /feed/api/v1/

# Turn off default Spring Boot Solr health indicator
# (uses wrong URL)

